// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: channel/channel/commitment.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Commitment struct {
	Index         string      `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	MultisigAddr  string      `protobuf:"bytes,2,opt,name=multisigAddr,proto3" json:"multisigAddr,omitempty"`
	Creatoraddr   string      `protobuf:"bytes,3,opt,name=creatoraddr,proto3" json:"creatoraddr,omitempty"`
	Partneraddr   string      `protobuf:"bytes,4,opt,name=partneraddr,proto3" json:"partneraddr,omitempty"`
	Hashcode      string      `protobuf:"bytes,5,opt,name=hashcode,proto3" json:"hashcode,omitempty"`
	Numblock      uint64      `protobuf:"varint,6,opt,name=numblock,proto3" json:"numblock,omitempty"`
	Cointocreator *types.Coin `protobuf:"bytes,7,opt,name=cointocreator,proto3" json:"cointocreator,omitempty"`
	Cointohtlc    *types.Coin `protobuf:"bytes,8,opt,name=cointohtlc,proto3" json:"cointohtlc,omitempty"`
	Channelid     string      `protobuf:"bytes,9,opt,name=channelid,proto3" json:"channelid,omitempty"`
}

func (m *Commitment) Reset()         { *m = Commitment{} }
func (m *Commitment) String() string { return proto.CompactTextString(m) }
func (*Commitment) ProtoMessage()    {}
func (*Commitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_461fecda49b4d244, []int{0}
}
func (m *Commitment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Commitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Commitment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Commitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commitment.Merge(m, src)
}
func (m *Commitment) XXX_Size() int {
	return m.Size()
}
func (m *Commitment) XXX_DiscardUnknown() {
	xxx_messageInfo_Commitment.DiscardUnknown(m)
}

var xxx_messageInfo_Commitment proto.InternalMessageInfo

func (m *Commitment) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Commitment) GetMultisigAddr() string {
	if m != nil {
		return m.MultisigAddr
	}
	return ""
}

func (m *Commitment) GetCreatoraddr() string {
	if m != nil {
		return m.Creatoraddr
	}
	return ""
}

func (m *Commitment) GetPartneraddr() string {
	if m != nil {
		return m.Partneraddr
	}
	return ""
}

func (m *Commitment) GetHashcode() string {
	if m != nil {
		return m.Hashcode
	}
	return ""
}

func (m *Commitment) GetNumblock() uint64 {
	if m != nil {
		return m.Numblock
	}
	return 0
}

func (m *Commitment) GetCointocreator() *types.Coin {
	if m != nil {
		return m.Cointocreator
	}
	return nil
}

func (m *Commitment) GetCointohtlc() *types.Coin {
	if m != nil {
		return m.Cointohtlc
	}
	return nil
}

func (m *Commitment) GetChannelid() string {
	if m != nil {
		return m.Channelid
	}
	return ""
}

func init() {
	proto.RegisterType((*Commitment)(nil), "channel.channel.Commitment")
}

func init() { proto.RegisterFile("channel/channel/commitment.proto", fileDescriptor_461fecda49b4d244) }

var fileDescriptor_461fecda49b4d244 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xeb, 0xfe, 0x6d, 0xff, 0xd6, 0x05, 0x21, 0x59, 0x48, 0x98, 0x0a, 0x59, 0x51, 0xa7,
	0x4e, 0x8e, 0x02, 0x13, 0x13, 0x82, 0xbe, 0x41, 0x46, 0x36, 0xc7, 0xb1, 0x88, 0x45, 0x6c, 0x47,
	0xb1, 0x8b, 0xca, 0x5b, 0xf0, 0x58, 0x8c, 0x1d, 0x19, 0x18, 0x50, 0xf2, 0x22, 0x28, 0x71, 0x08,
	0xe9, 0xc4, 0x74, 0x75, 0xcf, 0xf9, 0xae, 0xed, 0xe3, 0x0b, 0x03, 0x9e, 0x31, 0xad, 0x45, 0x1e,
	0xf6, 0xd5, 0x28, 0x25, 0x9d, 0x12, 0xda, 0xd1, 0xa2, 0x34, 0xce, 0xa0, 0xb3, 0xce, 0xa1, 0x5d,
	0x5d, 0x11, 0x6e, 0xac, 0x32, 0x36, 0x4c, 0x98, 0x15, 0xe1, 0x4b, 0x94, 0x08, 0xc7, 0xa2, 0x90,
	0x1b, 0xa9, 0xfd, 0xc0, 0xfa, 0x73, 0x0c, 0xe1, 0xb6, 0x3f, 0x05, 0x9d, 0xc3, 0xa9, 0xd4, 0xa9,
	0xd8, 0x63, 0x10, 0x80, 0xcd, 0x22, 0xf6, 0x0d, 0x5a, 0xc3, 0x13, 0xb5, 0xcb, 0x9d, 0xb4, 0xf2,
	0xe9, 0x3e, 0x4d, 0x4b, 0x3c, 0x6e, 0xcd, 0x23, 0x0d, 0x05, 0x70, 0xc9, 0x4b, 0xc1, 0x9c, 0x29,
	0x59, 0x83, 0xfc, 0x6b, 0x91, 0xa1, 0xd4, 0x10, 0x05, 0x2b, 0x9d, 0x16, 0x9e, 0x98, 0x78, 0x62,
	0x20, 0xa1, 0x15, 0x9c, 0x67, 0xcc, 0x66, 0xdc, 0xa4, 0x02, 0x4f, 0x5b, 0xbb, 0xef, 0x1b, 0x4f,
	0xef, 0x54, 0x92, 0x1b, 0xfe, 0x8c, 0x67, 0x01, 0xd8, 0x4c, 0xe2, 0xbe, 0x47, 0x77, 0xf0, 0xb4,
	0x89, 0xe4, 0x4c, 0x77, 0x1d, 0xfe, 0x1f, 0x80, 0xcd, 0xf2, 0xfa, 0x92, 0xfa, 0xf0, 0xb4, 0x09,
	0x4f, 0xbb, 0xf0, 0x74, 0x6b, 0xa4, 0x8e, 0x8f, 0x79, 0x74, 0x0b, 0xa1, 0x17, 0x32, 0x97, 0x73,
	0x3c, 0xff, 0x6b, 0x7a, 0x00, 0xa3, 0x2b, 0xb8, 0xe8, 0xfe, 0x5a, 0xa6, 0x78, 0xd1, 0x3e, 0xfa,
	0x57, 0x78, 0x88, 0xde, 0x2b, 0x02, 0x0e, 0x15, 0x01, 0x5f, 0x15, 0x01, 0x6f, 0x35, 0x19, 0x1d,
	0x6a, 0x32, 0xfa, 0xa8, 0xc9, 0xe8, 0xf1, 0xe2, 0x67, 0x87, 0xfb, 0x7e, 0x9b, 0xee, 0xb5, 0x10,
	0x36, 0x99, 0xb5, 0x8b, 0xb9, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x48, 0x18, 0xa9, 0xed,
	0x01, 0x00, 0x00,
}

func (m *Commitment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Commitment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Commitment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Channelid) > 0 {
		i -= len(m.Channelid)
		copy(dAtA[i:], m.Channelid)
		i = encodeVarintCommitment(dAtA, i, uint64(len(m.Channelid)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Cointohtlc != nil {
		{
			size, err := m.Cointohtlc.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCommitment(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.Cointocreator != nil {
		{
			size, err := m.Cointocreator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCommitment(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.Numblock != 0 {
		i = encodeVarintCommitment(dAtA, i, uint64(m.Numblock))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Hashcode) > 0 {
		i -= len(m.Hashcode)
		copy(dAtA[i:], m.Hashcode)
		i = encodeVarintCommitment(dAtA, i, uint64(len(m.Hashcode)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Partneraddr) > 0 {
		i -= len(m.Partneraddr)
		copy(dAtA[i:], m.Partneraddr)
		i = encodeVarintCommitment(dAtA, i, uint64(len(m.Partneraddr)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Creatoraddr) > 0 {
		i -= len(m.Creatoraddr)
		copy(dAtA[i:], m.Creatoraddr)
		i = encodeVarintCommitment(dAtA, i, uint64(len(m.Creatoraddr)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MultisigAddr) > 0 {
		i -= len(m.MultisigAddr)
		copy(dAtA[i:], m.MultisigAddr)
		i = encodeVarintCommitment(dAtA, i, uint64(len(m.MultisigAddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintCommitment(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommitment(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommitment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Commitment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovCommitment(uint64(l))
	}
	l = len(m.MultisigAddr)
	if l > 0 {
		n += 1 + l + sovCommitment(uint64(l))
	}
	l = len(m.Creatoraddr)
	if l > 0 {
		n += 1 + l + sovCommitment(uint64(l))
	}
	l = len(m.Partneraddr)
	if l > 0 {
		n += 1 + l + sovCommitment(uint64(l))
	}
	l = len(m.Hashcode)
	if l > 0 {
		n += 1 + l + sovCommitment(uint64(l))
	}
	if m.Numblock != 0 {
		n += 1 + sovCommitment(uint64(m.Numblock))
	}
	if m.Cointocreator != nil {
		l = m.Cointocreator.Size()
		n += 1 + l + sovCommitment(uint64(l))
	}
	if m.Cointohtlc != nil {
		l = m.Cointohtlc.Size()
		n += 1 + l + sovCommitment(uint64(l))
	}
	l = len(m.Channelid)
	if l > 0 {
		n += 1 + l + sovCommitment(uint64(l))
	}
	return n
}

func sovCommitment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommitment(x uint64) (n int) {
	return sovCommitment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Commitment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommitment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Commitment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Commitment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultisigAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultisigAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creatoraddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creatoraddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Partneraddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Partneraddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hashcode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hashcode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Numblock", wireType)
			}
			m.Numblock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Numblock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cointocreator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCommitment
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Cointocreator == nil {
				m.Cointocreator = &types.Coin{}
			}
			if err := m.Cointocreator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cointohtlc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCommitment
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Cointohtlc == nil {
				m.Cointohtlc = &types.Coin{}
			}
			if err := m.Cointohtlc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channelid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channelid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommitment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommitment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommitment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommitment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommitment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommitment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommitment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommitment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommitment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommitment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommitment = fmt.Errorf("proto: unexpected end of group")
)
