// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: channel/channel/fwdcommitment.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Fwdcommitment struct {
	Index            string        `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Channelid        string        `protobuf:"bytes,2,opt,name=channelid,proto3" json:"channelid,omitempty"`
	MultisigAddr     string        `protobuf:"bytes,3,opt,name=multisigAddr,proto3" json:"multisigAddr,omitempty"`
	SenderAddr       string        `protobuf:"bytes,4,opt,name=senderAddr,proto3" json:"senderAddr,omitempty"`
	ReceiverAddr     string        `protobuf:"bytes,5,opt,name=receiverAddr,proto3" json:"receiverAddr,omitempty"`
	Timelocksender   uint64        `protobuf:"varint,6,opt,name=timelocksender,proto3" json:"timelocksender,omitempty"`
	Timelockreceiver uint64        `protobuf:"varint,7,opt,name=timelockreceiver,proto3" json:"timelockreceiver,omitempty"`
	Hashcodehtlc     string        `protobuf:"bytes,8,opt,name=hashcodehtlc,proto3" json:"hashcodehtlc,omitempty"`
	Hashcodedest     string        `protobuf:"bytes,9,opt,name=hashcodedest,proto3" json:"hashcodedest,omitempty"`
	Cointransfer     []*types.Coin `protobuf:"bytes,10,rep,name=cointransfer,proto3" json:"cointransfer,omitempty"`
	Creator          string        `protobuf:"bytes,11,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Fwdcommitment) Reset()         { *m = Fwdcommitment{} }
func (m *Fwdcommitment) String() string { return proto.CompactTextString(m) }
func (*Fwdcommitment) ProtoMessage()    {}
func (*Fwdcommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fe370908b866a42, []int{0}
}
func (m *Fwdcommitment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fwdcommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fwdcommitment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fwdcommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fwdcommitment.Merge(m, src)
}
func (m *Fwdcommitment) XXX_Size() int {
	return m.Size()
}
func (m *Fwdcommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_Fwdcommitment.DiscardUnknown(m)
}

var xxx_messageInfo_Fwdcommitment proto.InternalMessageInfo

func (m *Fwdcommitment) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Fwdcommitment) GetChannelid() string {
	if m != nil {
		return m.Channelid
	}
	return ""
}

func (m *Fwdcommitment) GetMultisigAddr() string {
	if m != nil {
		return m.MultisigAddr
	}
	return ""
}

func (m *Fwdcommitment) GetSenderAddr() string {
	if m != nil {
		return m.SenderAddr
	}
	return ""
}

func (m *Fwdcommitment) GetReceiverAddr() string {
	if m != nil {
		return m.ReceiverAddr
	}
	return ""
}

func (m *Fwdcommitment) GetTimelocksender() uint64 {
	if m != nil {
		return m.Timelocksender
	}
	return 0
}

func (m *Fwdcommitment) GetTimelockreceiver() uint64 {
	if m != nil {
		return m.Timelockreceiver
	}
	return 0
}

func (m *Fwdcommitment) GetHashcodehtlc() string {
	if m != nil {
		return m.Hashcodehtlc
	}
	return ""
}

func (m *Fwdcommitment) GetHashcodedest() string {
	if m != nil {
		return m.Hashcodedest
	}
	return ""
}

func (m *Fwdcommitment) GetCointransfer() []*types.Coin {
	if m != nil {
		return m.Cointransfer
	}
	return nil
}

func (m *Fwdcommitment) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Fwdcommitment)(nil), "channel.channel.Fwdcommitment")
}

func init() {
	proto.RegisterFile("channel/channel/fwdcommitment.proto", fileDescriptor_2fe370908b866a42)
}

var fileDescriptor_2fe370908b866a42 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcb, 0x4a, 0x33, 0x31,
	0x18, 0x86, 0x3b, 0x7f, 0x4f, 0x7f, 0xd3, 0x7a, 0x20, 0x08, 0x46, 0x91, 0x50, 0x2a, 0x48, 0x71,
	0x31, 0x43, 0x75, 0xed, 0x42, 0x05, 0x2f, 0xa0, 0x4b, 0x77, 0xd3, 0xe4, 0xab, 0x13, 0x9c, 0x49,
	0x4a, 0x12, 0x6b, 0xbd, 0x0b, 0x2f, 0xc1, 0xcb, 0x71, 0xd9, 0xa5, 0x4b, 0x69, 0x6f, 0x44, 0x26,
	0x99, 0xd1, 0x19, 0x5d, 0x85, 0x3c, 0x79, 0xbe, 0x37, 0x90, 0x37, 0xe8, 0x94, 0x25, 0xb1, 0x94,
	0x90, 0x46, 0xe5, 0x3a, 0x7f, 0xe6, 0x4c, 0x65, 0x99, 0xb0, 0x19, 0x48, 0x1b, 0x2e, 0xb4, 0xb2,
	0x0a, 0xef, 0x15, 0x87, 0x61, 0xb1, 0x1e, 0x53, 0xa6, 0x4c, 0xa6, 0x4c, 0x34, 0x8b, 0x0d, 0x44,
	0xcb, 0xc9, 0x0c, 0x6c, 0x3c, 0x89, 0x98, 0x12, 0xd2, 0x0f, 0x8c, 0xde, 0x9a, 0x68, 0xe7, 0xae,
	0x1a, 0x84, 0x0f, 0x50, 0x5b, 0x48, 0x0e, 0x2b, 0x12, 0x0c, 0x83, 0x71, 0x6f, 0xea, 0x37, 0xf8,
	0x04, 0xf5, 0x8a, 0x48, 0xc1, 0xc9, 0x3f, 0x77, 0xf2, 0x03, 0xf0, 0x08, 0x0d, 0xb2, 0xa7, 0xd4,
	0x0a, 0x23, 0x1e, 0xae, 0x39, 0xd7, 0xa4, 0xe9, 0x84, 0x1a, 0xc3, 0x14, 0x21, 0x03, 0x92, 0x83,
	0x76, 0x46, 0xcb, 0x19, 0x15, 0x92, 0x67, 0x68, 0x60, 0x20, 0x96, 0x85, 0xd1, 0xf6, 0x19, 0x55,
	0x86, 0xcf, 0xd0, 0xae, 0x15, 0x19, 0xa4, 0x8a, 0x3d, 0xfa, 0x49, 0xd2, 0x19, 0x06, 0xe3, 0xd6,
	0xf4, 0x17, 0xc5, 0xe7, 0x68, 0xbf, 0x24, 0xe5, 0x3c, 0xe9, 0x3a, 0xf3, 0x0f, 0xcf, 0xef, 0x4d,
	0x62, 0x93, 0x30, 0xc5, 0x21, 0xb1, 0x29, 0x23, 0xff, 0xfd, 0xbd, 0x55, 0x56, 0x75, 0x38, 0x18,
	0x4b, 0x7a, 0x75, 0x27, 0x67, 0xf8, 0x0a, 0x0d, 0xf2, 0x77, 0xb5, 0x3a, 0x96, 0x66, 0x0e, 0x9a,
	0xa0, 0x61, 0x73, 0xdc, 0xbf, 0x38, 0x0a, 0x7d, 0x01, 0x61, 0x5e, 0x40, 0x58, 0x14, 0x10, 0xde,
	0x2a, 0x21, 0xa7, 0x35, 0x1d, 0x13, 0xd4, 0x65, 0x1a, 0x62, 0xab, 0x34, 0xe9, 0xbb, 0xf4, 0x72,
	0x7b, 0x33, 0x79, 0xdf, 0xd0, 0x60, 0xbd, 0xa1, 0xc1, 0xe7, 0x86, 0x06, 0xaf, 0x5b, 0xda, 0x58,
	0x6f, 0x69, 0xe3, 0x63, 0x4b, 0x1b, 0xf7, 0x87, 0xe5, 0x57, 0x58, 0x7d, 0x7f, 0x0a, 0xfb, 0xb2,
	0x00, 0x33, 0xeb, 0xb8, 0x72, 0x2f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xc5, 0xf5, 0xf8,
	0x34, 0x02, 0x00, 0x00,
}

func (m *Fwdcommitment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fwdcommitment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fwdcommitment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintFwdcommitment(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Cointransfer) > 0 {
		for iNdEx := len(m.Cointransfer) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Cointransfer[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFwdcommitment(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.Hashcodedest) > 0 {
		i -= len(m.Hashcodedest)
		copy(dAtA[i:], m.Hashcodedest)
		i = encodeVarintFwdcommitment(dAtA, i, uint64(len(m.Hashcodedest)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Hashcodehtlc) > 0 {
		i -= len(m.Hashcodehtlc)
		copy(dAtA[i:], m.Hashcodehtlc)
		i = encodeVarintFwdcommitment(dAtA, i, uint64(len(m.Hashcodehtlc)))
		i--
		dAtA[i] = 0x42
	}
	if m.Timelockreceiver != 0 {
		i = encodeVarintFwdcommitment(dAtA, i, uint64(m.Timelockreceiver))
		i--
		dAtA[i] = 0x38
	}
	if m.Timelocksender != 0 {
		i = encodeVarintFwdcommitment(dAtA, i, uint64(m.Timelocksender))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ReceiverAddr) > 0 {
		i -= len(m.ReceiverAddr)
		copy(dAtA[i:], m.ReceiverAddr)
		i = encodeVarintFwdcommitment(dAtA, i, uint64(len(m.ReceiverAddr)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SenderAddr) > 0 {
		i -= len(m.SenderAddr)
		copy(dAtA[i:], m.SenderAddr)
		i = encodeVarintFwdcommitment(dAtA, i, uint64(len(m.SenderAddr)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MultisigAddr) > 0 {
		i -= len(m.MultisigAddr)
		copy(dAtA[i:], m.MultisigAddr)
		i = encodeVarintFwdcommitment(dAtA, i, uint64(len(m.MultisigAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Channelid) > 0 {
		i -= len(m.Channelid)
		copy(dAtA[i:], m.Channelid)
		i = encodeVarintFwdcommitment(dAtA, i, uint64(len(m.Channelid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintFwdcommitment(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFwdcommitment(dAtA []byte, offset int, v uint64) int {
	offset -= sovFwdcommitment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Fwdcommitment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovFwdcommitment(uint64(l))
	}
	l = len(m.Channelid)
	if l > 0 {
		n += 1 + l + sovFwdcommitment(uint64(l))
	}
	l = len(m.MultisigAddr)
	if l > 0 {
		n += 1 + l + sovFwdcommitment(uint64(l))
	}
	l = len(m.SenderAddr)
	if l > 0 {
		n += 1 + l + sovFwdcommitment(uint64(l))
	}
	l = len(m.ReceiverAddr)
	if l > 0 {
		n += 1 + l + sovFwdcommitment(uint64(l))
	}
	if m.Timelocksender != 0 {
		n += 1 + sovFwdcommitment(uint64(m.Timelocksender))
	}
	if m.Timelockreceiver != 0 {
		n += 1 + sovFwdcommitment(uint64(m.Timelockreceiver))
	}
	l = len(m.Hashcodehtlc)
	if l > 0 {
		n += 1 + l + sovFwdcommitment(uint64(l))
	}
	l = len(m.Hashcodedest)
	if l > 0 {
		n += 1 + l + sovFwdcommitment(uint64(l))
	}
	if len(m.Cointransfer) > 0 {
		for _, e := range m.Cointransfer {
			l = e.Size()
			n += 1 + l + sovFwdcommitment(uint64(l))
		}
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovFwdcommitment(uint64(l))
	}
	return n
}

func sovFwdcommitment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFwdcommitment(x uint64) (n int) {
	return sovFwdcommitment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Fwdcommitment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFwdcommitment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fwdcommitment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fwdcommitment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channelid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channelid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultisigAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultisigAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiverAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timelocksender", wireType)
			}
			m.Timelocksender = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timelocksender |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timelockreceiver", wireType)
			}
			m.Timelockreceiver = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timelockreceiver |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hashcodehtlc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hashcodehtlc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hashcodedest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hashcodedest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cointransfer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cointransfer = append(m.Cointransfer, &types.Coin{})
			if err := m.Cointransfer[len(m.Cointransfer)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFwdcommitment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFwdcommitment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFwdcommitment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFwdcommitment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFwdcommitment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFwdcommitment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFwdcommitment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFwdcommitment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFwdcommitment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFwdcommitment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFwdcommitment = fmt.Errorf("proto: unexpected end of group")
)
