// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: channel/channel/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgOpenchannel struct {
	Creator      string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PartA        string      `protobuf:"bytes,2,opt,name=partA,proto3" json:"partA,omitempty"`
	PartB        string      `protobuf:"bytes,3,opt,name=partB,proto3" json:"partB,omitempty"`
	CoinA        *types.Coin `protobuf:"bytes,4,opt,name=coinA,proto3" json:"coinA,omitempty"`
	CoinB        *types.Coin `protobuf:"bytes,5,opt,name=coinB,proto3" json:"coinB,omitempty"`
	MultisigAddr string      `protobuf:"bytes,6,opt,name=multisigAddr,proto3" json:"multisigAddr,omitempty"`
	Sequence     string      `protobuf:"bytes,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *MsgOpenchannel) Reset()         { *m = MsgOpenchannel{} }
func (m *MsgOpenchannel) String() string { return proto.CompactTextString(m) }
func (*MsgOpenchannel) ProtoMessage()    {}
func (*MsgOpenchannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_89a552858311affe, []int{0}
}
func (m *MsgOpenchannel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgOpenchannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgOpenchannel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgOpenchannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOpenchannel.Merge(m, src)
}
func (m *MsgOpenchannel) XXX_Size() int {
	return m.Size()
}
func (m *MsgOpenchannel) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOpenchannel.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOpenchannel proto.InternalMessageInfo

func (m *MsgOpenchannel) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgOpenchannel) GetPartA() string {
	if m != nil {
		return m.PartA
	}
	return ""
}

func (m *MsgOpenchannel) GetPartB() string {
	if m != nil {
		return m.PartB
	}
	return ""
}

func (m *MsgOpenchannel) GetCoinA() *types.Coin {
	if m != nil {
		return m.CoinA
	}
	return nil
}

func (m *MsgOpenchannel) GetCoinB() *types.Coin {
	if m != nil {
		return m.CoinB
	}
	return nil
}

func (m *MsgOpenchannel) GetMultisigAddr() string {
	if m != nil {
		return m.MultisigAddr
	}
	return ""
}

func (m *MsgOpenchannel) GetSequence() string {
	if m != nil {
		return m.Sequence
	}
	return ""
}

type MsgOpenchannelResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgOpenchannelResponse) Reset()         { *m = MsgOpenchannelResponse{} }
func (m *MsgOpenchannelResponse) String() string { return proto.CompactTextString(m) }
func (*MsgOpenchannelResponse) ProtoMessage()    {}
func (*MsgOpenchannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89a552858311affe, []int{1}
}
func (m *MsgOpenchannelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgOpenchannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgOpenchannelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgOpenchannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOpenchannelResponse.Merge(m, src)
}
func (m *MsgOpenchannelResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgOpenchannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOpenchannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOpenchannelResponse proto.InternalMessageInfo

func (m *MsgOpenchannelResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgOpenchannel)(nil), "channel.channel.MsgOpenchannel")
	proto.RegisterType((*MsgOpenchannelResponse)(nil), "channel.channel.MsgOpenchannelResponse")
}

func init() { proto.RegisterFile("channel/channel/tx.proto", fileDescriptor_89a552858311affe) }

var fileDescriptor_89a552858311affe = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0xad, 0x5b, 0xda, 0x82, 0x8b, 0x8a, 0x64, 0x21, 0x30, 0x19, 0x4c, 0x95, 0x85, 0x4c, 0x8e,
	0x52, 0x7e, 0x41, 0xc2, 0x5c, 0x21, 0x65, 0x41, 0x62, 0x40, 0xca, 0x87, 0x15, 0x2c, 0xb5, 0x76,
	0x88, 0x5d, 0x54, 0xfe, 0x05, 0x3f, 0x8b, 0xb1, 0x23, 0x23, 0x4a, 0xfe, 0x04, 0x23, 0x6a, 0x12,
	0x53, 0xc2, 0x02, 0xd3, 0xe9, 0x9e, 0xef, 0xf9, 0xbd, 0xbb, 0x07, 0x71, 0xf2, 0x18, 0x09, 0xc1,
	0x96, 0xae, 0xa9, 0x7a, 0x43, 0xf3, 0x42, 0x6a, 0x89, 0x4e, 0x5a, 0x84, 0xb6, 0xd5, 0x22, 0x89,
	0x54, 0x2b, 0xa9, 0xdc, 0x38, 0x52, 0xcc, 0x7d, 0xf6, 0x62, 0xa6, 0x23, 0xcf, 0x4d, 0x24, 0x17,
	0x0d, 0xc1, 0xfe, 0x04, 0x70, 0xba, 0x50, 0xd9, 0x6d, 0xce, 0x44, 0x4b, 0x41, 0x18, 0x8e, 0x93,
	0x82, 0x45, 0x5a, 0x16, 0x18, 0xcc, 0x80, 0x73, 0x14, 0x9a, 0x16, 0x9d, 0xc2, 0x61, 0x1e, 0x15,
	0xda, 0xc7, 0xfd, 0x1a, 0x6f, 0x1a, 0x83, 0x06, 0x78, 0xb0, 0x47, 0x03, 0xe4, 0xc2, 0xe1, 0x4e,
	0xc6, 0xc7, 0x07, 0x33, 0xe0, 0x4c, 0xe6, 0x17, 0xb4, 0x31, 0x42, 0x77, 0x46, 0x68, 0x6b, 0x84,
	0xde, 0x48, 0x2e, 0xc2, 0x66, 0xce, 0x10, 0x02, 0x3c, 0xfc, 0x17, 0x21, 0x40, 0x36, 0x3c, 0x5e,
	0xad, 0x97, 0x9a, 0x2b, 0x9e, 0xf9, 0x69, 0x5a, 0xe0, 0x51, 0x2d, 0xdf, 0xc1, 0x90, 0x05, 0x0f,
	0x15, 0x7b, 0x5a, 0x33, 0x91, 0x30, 0x3c, 0xae, 0xdf, 0xbf, 0x7b, 0xdb, 0x81, 0x67, 0xdd, 0xcd,
	0x43, 0xa6, 0x72, 0x29, 0x14, 0x43, 0x53, 0xd8, 0xe7, 0x69, 0xbb, 0x7c, 0x9f, 0xa7, 0xf3, 0x07,
	0x38, 0x58, 0xa8, 0x0c, 0xdd, 0xc1, 0xc9, 0xcf, 0x3b, 0x5d, 0xd2, 0x5f, 0xc7, 0xa6, 0xdd, 0xef,
	0xac, 0xab, 0x3f, 0x06, 0x8c, 0x5e, 0xe0, 0xbd, 0x95, 0x04, 0x6c, 0x4b, 0x02, 0x3e, 0x4a, 0x02,
	0x5e, 0x2b, 0xd2, 0xdb, 0x56, 0xa4, 0xf7, 0x5e, 0x91, 0xde, 0xfd, 0xb9, 0x49, 0x78, 0xb3, 0xcf,
	0xfa, 0x25, 0x67, 0x2a, 0x1e, 0xd5, 0xf1, 0x5d, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x01, 0x5c,
	0x94, 0x79, 0x0b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	Openchannel(ctx context.Context, in *MsgOpenchannel, opts ...grpc.CallOption) (*MsgOpenchannelResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Openchannel(ctx context.Context, in *MsgOpenchannel, opts ...grpc.CallOption) (*MsgOpenchannelResponse, error) {
	out := new(MsgOpenchannelResponse)
	err := c.cc.Invoke(ctx, "/channel.channel.Msg/Openchannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	Openchannel(context.Context, *MsgOpenchannel) (*MsgOpenchannelResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Openchannel(ctx context.Context, req *MsgOpenchannel) (*MsgOpenchannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Openchannel not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Openchannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgOpenchannel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Openchannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/channel.channel.Msg/Openchannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Openchannel(ctx, req.(*MsgOpenchannel))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "channel.channel.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Openchannel",
			Handler:    _Msg_Openchannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "channel/channel/tx.proto",
}

func (m *MsgOpenchannel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgOpenchannel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgOpenchannel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sequence) > 0 {
		i -= len(m.Sequence)
		copy(dAtA[i:], m.Sequence)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sequence)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MultisigAddr) > 0 {
		i -= len(m.MultisigAddr)
		copy(dAtA[i:], m.MultisigAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MultisigAddr)))
		i--
		dAtA[i] = 0x32
	}
	if m.CoinB != nil {
		{
			size, err := m.CoinB.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.CoinA != nil {
		{
			size, err := m.CoinA.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.PartB) > 0 {
		i -= len(m.PartB)
		copy(dAtA[i:], m.PartB)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PartB)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PartA) > 0 {
		i -= len(m.PartA)
		copy(dAtA[i:], m.PartA)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PartA)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgOpenchannelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgOpenchannelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgOpenchannelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgOpenchannel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PartA)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PartB)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.CoinA != nil {
		l = m.CoinA.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.CoinB != nil {
		l = m.CoinB.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MultisigAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Sequence)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgOpenchannelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgOpenchannel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgOpenchannel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgOpenchannel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartA", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PartA = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartB", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PartB = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinA", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CoinA == nil {
				m.CoinA = &types.Coin{}
			}
			if err := m.CoinA.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinB", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CoinB == nil {
				m.CoinB = &types.Coin{}
			}
			if err := m.CoinB.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultisigAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultisigAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequence = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgOpenchannelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgOpenchannelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgOpenchannelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
